// src/lib/ui/buttons/ui-button.svelte
<script lang="ts">
	export let disabled: boolean = false;
	export let block: boolean = false;
	export let large: boolean = false;
</script>

<button
	class:disabled:bg-beta={disabled}
	class:w-full={block}
	class={`bg-alpha hover:opacity-[0.9] text-[white] text-[12px] leading-[16px] font-bold  px-4 rounded-[8px] 
      ${large ? 'py-[16px]' : 'py-[8px]'}`}
	{disabled}
>
	<slot />
</button>

// src/ui/buttons/ui-button.tsx
import React from 'react'

interface ButtonProps {
  disabled?: boolean
  onClick?: () => void
  block?: boolean
  large?: boolean
}

const UIButton: React.FC<ButtonProps> = ({
  disabled,
  onClick,
  children,
  block,
  large
}) => {
  return (
    <button
      className={`bg-alpha hover:opacity-[0.9] text-[white] text-[12px] leading-[16px] font-bold  px-4 rounded-[8px] ${
        disabled ? 'disabled:bg-beta' : ''
      } ${block ? 'w-full' : ''} ${large ? 'py-[16px]' : 'py-[8px]'}`}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  )
}

export default UIButton
