// src/lib/ui/navbar/ui-navbar.svelte
<div class="relative flex items-center justify-between -mx-4 px-3 py-3 bg-white text-[#212121] shadow-custom-light">
  <div class="w-1/8 text-left">
    <slot name="leftIcon" />
  </div>
  <div class="w-1/2 absolute left-[50%] translate-x-[-50%] text-center">
    <slot />
  </div>
  <div class="w-1/8 text-right">
    <slot name="rightIcon" />
  </div>
</div>

// src/ui/navbar/ui-navbar.tsx
import React, { FC, ReactNode } from 'react'

type NavbarProps = {
  leftIcon?: ReactNode
  rightIcon?: ReactNode
  centerContent: ReactNode
}

const UINavbar: FC<NavbarProps> = ({ leftIcon, rightIcon, centerContent }) => {
  return (
    <div className="relative flex items-center justify-between -mx-4 px-3 py-3 bg-white text-[#212121] shadow-custom-light">
      <div className="w-1/8 text-left">{leftIcon}</div>
      <div className="w-1/2 absolute left-[50%] translate-x-[-50%] text-center">
        {centerContent}
      </div>
      <div className="w-1/8 text-right">{rightIcon}</div>
    </div>
  )
}

export default UINavbar
